variables:
  major-version: 1
  minor-version: 1
  patch-version: 9

  branch-suffix: $[ replace(replace(eq(variables['Build.SourceBranchName'], 'release'), 'True', ''), 'False', format('-{0}', variables['Build.SourceBranchName'])) ]
  major-minor-version: $[ format('{0}.{1}', variables['major-version'], variables['minor-version']) ]
  base-version: $[ format('{0}.{1}.{2}', variables['major-version'], variables['minor-version'], variables['patch-version']) ]
  base-version-with-branch: $[ format('{0}.{1}.{2}{3}', variables['major-version'], variables['minor-version'], variables['patch-version'], variables['branch-suffix']) ]

  revision-version: $[counter(variables['base-version-with-branch'], 0)]
  revision-suffix: $[ replace(replace(eq(variables['revision-version'], 0), 'True', ''), 'False', format('-p{0}', variables['revision-version'])) ]
  squilversion: $[ format('{0}{1}', variables['base-version'], variables['revision-suffix']) ]
  squilmauiversion: $[ format('{0}.0', variables['base-version'] ) ]

  is-main-release: and(eq(variables['revision-version'], 0), eq(variables['Build.SourceBranchName'], 'release'))

  squildockertags: |
    $(major-minor-version)
    $(squilversion)
    $[ replace(replace(variables['is-main-release'], 'True', 'latest'), 'False', '') ]

trigger:
- release

pool:
  vmImage: ubuntu-latest

stages:

- stage: BuildWeb
  jobs:
  - job: build
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'version.ps1'
        showWarnings: true
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifact: 'sources'
        publishLocation: 'pipeline'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/Squil.Web.csproj'
        arguments: '-o web-package'
        publishWebProjects: false
        zipAfterPublish: false
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'web-package'
        artifact: 'web'
        publishLocation: 'pipeline'

- stage: ReleaseWeb
  dependsOn: BuildWeb
  condition: eq(variables['Build.SourceBranchName'], 'release')
  jobs:
  - job: Docker
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'web'
        targetPath: '$(Build.SourcesDirectory)'
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 'Squil Docker Hub'
        repository: squiltech/squil
        tags: $(squildockertags)
  - job: Demo
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'web'
        targetPath: 'web'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'dir'
        workingDirectory: 'web'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(WebDemoSubscriptionName)'
        appType: 'webAppLinux'
        WebAppName: 'squil-staging'
        packageForLinux: 'web/Squil.Web'

- stage: BuildMauiWindows
  condition: eq(variables['revision-version'], 0)
  pool:
    vmImage: windows-latest
  jobs:
  - job: build
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'sources'
          targetPath: 'sources'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/Squil.Maui.csproj'
          arguments: '-f net6.0-windows10.0.19041.0'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)'
          Contents: '**/Squil.Maui*.msix'
          TargetFolder: 'maui-windows-package'
          flattenFolders: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'maui-windows-package'
          artifact: 'maui-windows-msix'
          publishLocation: 'pipeline'

- stage: ReleaseMauiWindows
  dependsOn: BuildMauiWindows
  jobs:
  - job: ReleaseToStore
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'web'
        targetPath: '$(Build.SourcesDirectory)'
    - task: store-publish@0
      inputs:
        serviceEndpoint: 'microsoft-store-deployment'
        appId: '$(MicrosoftStoreAppId)'
        packagePath: '**/*.msix'
        skipPolling: true
