variables:
  base-version: '1.1.9'
  build-suffix: $[counter(variables['base-version'], 1)]
  version: $[ format('{0}.{1}', variables['base-version'], variables['build-suffix']) ]

trigger:
- release

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    filePath: 'version.ps1'
    showWarnings: true
    workingDirectory: '$(Build.SourcesDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'sources'
    publishLocation: 'pipeline'
