trigger:
- master

pool:
  vmImage: ubuntu-latest

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    publishWebProjects: true

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: web'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
