trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: 'Squil.Maui'
- task: DotNetCoreCLI@2 # Doesn't ignore Maui for some reason
  inputs:
    command: 'publish'
    projects: 'Squil'
    arguments: '-o $(Build.ArtifactStagingDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'publish'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
