variables:
  base-version: '1.1.9'
  build-suffix: $[counter(variables['base-version'], 1)]
  squilversion: $[ format('{0}.{1}', variables['base-version'], variables['build-suffix']) ]
  squilmauiversion: $[ format('{0}.0', variables['base-version'] ) ]

trigger:
- release

pool:
  vmImage: ubuntu-latest

stages:

- stage: BuildWeb
  jobs:
  - job: build
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'version.ps1'
        showWarnings: true
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifact: 'sources'
        publishLocation: 'pipeline'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/Squil.Web.csproj'
        arguments: '-o web-package'
        publishWebProjects: false
        zipAfterPublish: false
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'web-package'
        artifact: 'web'
        publishLocation: 'pipeline'

- stage: BuildMauiWindows
  pool:
    vmImage: windows-latest
  jobs:
  - job: build
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'sources'
          targetPath: 'sources'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/Squil.Maui.csproj'
          arguments: '-f net6.0-windows10.0.19041.0'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)'
          Contents: '**/Squil.Maui*.msix'
          TargetFolder: 'maui-windows-package'
          flattenFolders: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'maui-windows-package'
          artifact: 'maui-windows-msix'
          publishLocation: 'pipeline'

- stage: ReleaseWeb
  dependsOn: BuildWeb
  jobs:
  - job: Docker
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'web'
        targetPath: '$(Build.SourcesDirectory)'
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 'Squil Docker Hub'
        repository: squiltech/squil
        tags: |
          $(squilversion)
  - job: Demo
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'web'
        targetPath: '$(Build.SourcesDirectory)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(WebDemoSubscriptionName)'
        appType: webAppLinux
        WebAppName: squil-staging

- stage: ReleaseMauiWindows
  dependsOn: BuildMauiWindows
  jobs:
  - job: ReleaseToStore
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'web'
        targetPath: '$(Build.SourcesDirectory)'
    - task: MS-RDX-MRO.windows-store-publish.publish-task.store-publish@0
      displayName: 'Publish to store'
      inputs:
        serviceEndpoint: 'microsoft-store-deployment'
        appId: '$(MicrosoftStoreAppId)'
        packagePath: '**/*.msix'
