variables:
  base-version: '1.1.9'
  build-suffix: $[counter(variables['base-version'], 1)]
  version: $[ format('{0}.{1}', variables['base-version'], variables['build-suffix']) ]
  maui-version: $[ format('{0}.0', variables['base-version'] ) ]

trigger:
- release

pool:
  name: Ubuntu
  vmImage: ubuntu-latest

stages:
- stage: Prepare
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: prepare
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'version.ps1'
        showWarnings: true
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifact: 'sources'
        publishLocation: 'pipeline'
- stage: MAUI
  pool:
    vmImage: windows-latest
  jobs:
  - job: build
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'sources'
          targetPath: 'sources'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/Squil.Maui.csproj'
          arguments: '-f net6.0-windows10.0.19041.0'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)'
          Contents: '**/Squil.Maui*.msix'
          TargetFolder: 'maui-windows-package'
          flattenFolders: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'maui-windows-package'
          artifact: 'maui-windows-msix'
          publishLocation: 'pipeline'
