trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2 # Doesn't ignore Maui for some reason
  inputs:
    workingDirectory: 'Nucleus'
    command: 'publish'
    projects: 'Squil.Web'
    arguments: '-o $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: web'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
